### ISSUE TITLE
[Refactor]: ShortTermHistory is confusing - refactoring could be useful

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#3489] opened 2024-08-20 09:23 UTC
**Summary**

I was trying to better understand how the event stream works, and looked at `ShortTermHistory`, and the class is a bit confusing I think: https://github.com/All-Hands-AI/OpenHands/blob/0a3d46a90b4a390180d33381c94cc98c88e36f48/openhands/memory/history.py#L21

1. This class inherits from `list[Event]`, but I don't think that this list is ever used? This inheritance should probably just be removed.
2. The relationship between `ShortTermHistory` and `EventStream` is not very clear. I'm not sure why we need two classes, and can't just use the `EventStream`.

I feel that this could prorbably be refactored to make the class a bit more clear and intuitive. Just starting an issue here to track this for now.

**Comment by tobitege** [comment] 2024-08-20 09:44
For reference:
![grafik](https://github.com/user-attachments/assets/333dff75-5043-455e-8206-c00d89568577)

**Comment by enyst** [comment] 2024-09-06 18:04
Closing as duplicate of https://github.com/All-Hands-AI/OpenHands/issues/3731. Please feel free to reopen if you disagree.

**Closed by enyst** 2024-09-06 18:04 UTC
