### ISSUE TITLE
[Bug]: LLM-related settings fail to be saved

### ISSUE THREAD

**Issue by avi12** [All-Hands-AI/OpenHands#5837] opened 2024-12-26 19:59 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

https://github.com/user-attachments/assets/b012309e-0e1c-4fab-a1bd-35bc9f6ad8d3

### OpenHands Installation

Docker command in README

### OpenHands Version

`main`

### Operating System
Windows 10

**Comment by avi12** [comment] 2024-12-26 20:43
Interestingly enough, I cannot reproduce the issue when I set in the Docker command to pull the image of 0.17

**Comment by mamoodi** [comment] 2024-12-26 21:05
@avi12 yep thanks for bringing this up. Looks like a regression on main

**Comment by mamoodi** [comment] 2024-12-26 21:06
@tofarr you had a PR go in recently to migrate settings?
Can you take a look?

Aside from the issue reported, seems like it now expects the security analyzer to be set as well.

**Comment by rbren** [comment] 2024-12-26 21:16
@avi12 the `docker run` command changed recently. Can you share the exact command you ran?

**Comment by avi12** [comment] 2024-12-26 21:38
```powershell
docker run
  -p 3000:3000
  --env LOG_ALL_EVENTS=true
  --env SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:main-nikolaik
  --env WORKSPACE_MOUNT_PATH=C:\repositories\extensions\youtube-time-manager
  --name openhands-app
  --pull always
  --add-host host.docker.internal:host-gateway
  -v C:/repositories/extensions/youtube-time-manager:/opt/workspace_base
  -v /var/run/docker.sock:/var/run/docker.sock
  --rm
  docker.all-hands.dev/all-hands-ai/openhands:0.17 
```

**Comment by enyst** [comment] 2024-12-27 00:58
Expecting the security analyzer should be fixed now in main.

**Comment by mamoodi** [comment] 2024-12-27 16:37
This should be resolved in main. Just one small note right now that @amanape will work on fixing in a follow up.
The API KEY will show empty in the UI even if you set it. It works though. Just shows empty in UI.

**Comment by mamoodi** [comment] 2024-12-30 18:08
This actually never made it to the previous release and is fixed on main. Closing.

**Closed by mamoodi** 2024-12-30 18:08 UTC
Labels: bug, severity:critical

**Comment by avi12** [comment] 2025-01-01 20:54
The bug occurs when I'm in the `main` branch, as of https://github.com/All-Hands-AI/OpenHands/commit/3d4d66a8c2f6bbf403fde8f3d607b51e9570557c

**Comment by amanape** [comment] 2025-01-02 12:40
Could you try once more with the latest release? We've updated some things in settings since then

**Comment by avi12** [comment] 2025-01-02 13:41
Is this the desired behavior? I'd expect the key be in the `<input type="password">`
![image](https://github.com/user-attachments/assets/8c4127fa-6cba-49da-a2be-6dea1e49f26a)

**Comment by avi12** [comment] 2025-01-02 14:15
When I build from source I have the opposite problem:
![image](https://github.com/user-attachments/assets/d301b790-f71d-410c-be08-27561ec8165c)

the API key is set both in the local storage AND `config.toml`
