### ISSUE TITLE
[Bug]: Github Resolver comment "workflow error" when the workflow is successful

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/OpenHands#5216] opened 2024-11-22 20:50 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

Example: https://github.com/All-Hands-AI/OpenHands/pull/5181#issuecomment-2494766867

### OpenHands Installation

Other

### Operating System

None

### Logs, Errors, Screenshots, and Additional Context

Error log:

The workflow to fix this issue encountered an error. Please check the workflow logs for more information.

**Comment by malhotra5** [comment] 2024-11-22 22:29
I've found one issue which was introduced in this [PR](https://github.com/All-Hands-AI/OpenHands/pull/5075)

`target-branch` parameter was added to the `Attempt to resolve issue` step instead of `Create draft PR or push branch` step in `.github/workflows/openhands-resolver.yml`

I think there may be one more bug, will keep digging

**Comment by enyst** [comment] 2024-11-25 01:52
The issue I linked looks like a duplicate of this. If you can confirm that, @malhotra5 , I'll just close it.

Example run where it clearly did everything right, just the JSON parsing says it was wrong, apparently:
https://github.com/All-Hands-AI/OpenHands/pull/5242#issuecomment-2496496749

**Comment by malhotra5** [comment] 2024-12-01 18:59
Hmm I don't think its a duplicate. This issue was a more severe case of the resolver failing midway through the workflow, which should be resolved now. Let's close this one and track the JSON decoding issues in #5234.

**Closed by malhotra5** 2024-12-01 18:59 UTC
Labels: bug, fix-me, resolver
