### ISSUE TITLE
[Bug]: Error when API key is not entered is not clear

### ISSUE THREAD

**Issue by neubig** [All-Hands-AI/OpenHands#4236] opened 2024-10-07 05:04 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the troubleshooting document at https://docs.all-hands.dev/modules/usage/troubleshooting
- [X] I have checked the existing issues.

### Describe the bug

In the frontend, if no API key has been entered, we should have a comprehensible error. However, if not API key is entered, we get an opaque error that just says "An error occurred while running the agent"

![image (2)](https://github.com/user-attachments/assets/456d9468-fa82-4b71-897e-904498b68709)
![image (1)](https://github.com/user-attachments/assets/103cdf4a-12b8-4b9a-ba85-7beed47a0a56)

This should be made more clear. @amanape , could you take a look at this?

### Current OpenHands version

```bash
0.9
```

### Installation and Configuration

```bash
docker?
```

### Logs, Errors, Screenshots, and Additional Context

See conversation on slack: https://openhands-ai.slack.com/archives/C06U8UTKSAD/p1728265897191799

**Comment by enyst** [comment] 2024-10-07 05:45
This seems a duplicate (particular case) of https://github.com/All-Hands-AI/OpenHands/issues/1451, and https://github.com/All-Hands-AI/OpenHands/issues/3739.

**Comment by neubig** [comment] 2024-10-07 05:48
Yeah, possibly. But I also think that maybe we shouldn't even be able to start entering text if the user hasn't entered an API key and selected a model.

**Comment by enyst** [comment] 2024-10-07 06:04
That makes sense, although I'd note that, personally, I took care for long to _not_ enforce a non-empty API key in the backend, kept it theoretically optional just as the API key is optional in liteLLM, because there are at least a few providers and set ups that don't need one. I seem to recall it supports at least [this scenario](https://github.com/All-Hands-AI/OpenHands/issues/1042), where Azure does not use an API key, but a vault.

In theory, we support such use cases too, although I am not aware of any success report yet and I don't have access to Azure myself to check.

We used to open the Settings window in the UI at the first run. That was intended to help the user set their credentials, doesn't that happen anymore?

On the other hand, I suppose it's not a big problem if we enforce even harsher that the user _must_ enter a dummy key at least... I can see why it makes sense from a usability for most uses cases point of view.

**Comment by amanape** [comment] 2024-10-07 06:39
I think it would be helpful to add some sort of indicator to let the user know there is a missing API key. The way the UI is currently set up makes it look like it is optional, and even if it were the case for some, most providers do require an API key anyways. Having the user change the setting mid session after realizing the error results in resetting the session and waiting to start a new one, which can be annoying.

We could introduce some sort of (!) or (?) symbol next to the settings icon if there is any missing setting that is important or requires the users attention.

We can also go all the way and disable the ability to start a new session until the API key is set IF liteLLM provides the information on which LLMs require it, and which do not

**Comment by enyst** [comment] 2024-10-13 18:54
> Having the user change the setting mid session after realizing the error results in resetting the session and waiting to start a new one, which can be annoying.

Well, if the key didn't work, it's the beginning... except, yes, for the time taken by the runtime. I am not sure we really have to restart it all... By the way, the new UI looks so slick!

> We can also go all the way and disable the ability to start a new session until the API key is set IF liteLLM provides the information on which LLMs require it, and which do not

Not that I know of 🤔 

A ! or ? symbol sounds good to me FWIW.

**Comment by rbren** [comment] 2024-10-14 14:50
IMO you should not be able to close the settings modal without an API key entered. Maybe if you enter "advanced" you can then close it (since maybe some private backends don't require a key)

I'd like to also put in some logic to _check_ the key before letting you close the modal, e.g. making a test call to the API

**Comment by tobitege** [comment] 2024-10-14 15:04
- Keeping a user trapped in a modal isn't ideal - they could've just "clicked around" to see what options exist.
- A test call should be optional via a button, not a requirement (do not cause cost without user consent)
- Most helpful way imo would be, as @enyst mentioned, a UI hint for the missing key (if not a local llm) for this.

**Comment by amanape** [comment] 2024-10-14 15:12
> Keeping a user trapped in a modal isn't ideal - they could've just "clicked around" to see what options exist.

An alternative would be a follow-up pop-up "Are you sure? You are about to proceed without an API key which [...]". Coupled with better error messages in the chat interface due to invalid API keys, we can't say we didn't warn them 🤷‍♂️

**Comment by Yashwanth-Chandrakumar** [comment] 2024-10-16 05:24
@amanape What if we could add an error toast or popup when the user exits the settings modal like an alert displaying "Are you sure? You are about to proceed without an API key you might not be able to use the agent" and so when the user confirms he can exit the modal even though he has not entered an api key.

We can also add a hanging fixed toast saying the API Keys is absent. If you have any other ideas please. I think i would do it,
 assign it to me.

**Comment by amanape** [comment] 2024-10-16 05:31
@Yashwanth-Chandrakumar After talking with the designer, the flow should be something like this:

1. User sees open settings modal (whether its as first time startup or they opened it from the sidebar)
2. User presses close without setting an API key
3. Another modal pops up saying "Are you sure [...]"
4. If the user presses "YES", both modals now close.
5. If the user presses "Cancel", go back to the settings modal and repeat from step 2 until they enter a key

This is for the settings modal, but we should probably improve display error messages from the backend (in a separate PR) displayed to the user from the chat interface. Currently we only say "an error occurred", which isn't the best indicator.

Feel free to take on the assignment, we have a couple of modals and components to build modals you can find around the app for reference.

**Closed** 2024-10-22 18:23 UTC
Labels: bug, frontend, severity:medium
