### ISSUE TITLE
[Bug]: Resolver fails to "Install OpenHands" when tagged with @openhands-agent on a comment on an PR without the "fix-me"

### ISSUE THREAD

**Issue by oconnorjoseph** [All-Hands-AI/OpenHands#5621] opened 2024-12-16 06:04 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

When the user tags @openhands-agent without a fix-me tag in the PR, the Resolver will leave a comment on the PR as if it will fix the issue. But it runs into the following error on the "Install OpenHands" job:
```
Run if [[ "" == "fix-me-experimental" ]] ||
/home/runner/work/_temp/4b187817-0de6-48c1-a0f0-cd08f3e6d9ce.sh: line 3: conditional binary operator expected
Error: Process completed with exit code 2.
```
Perhaps this error should be handled more gracefully, or the user should be able to tag the agent on PRs without the fix-me tag.

### OpenHands Installation

Docker command in README

### OpenHands Version

0.15.2

### Operating System

Linux

### Logs, Errors, Screenshots, and Additional Context

```
Run if [[ "" == "fix-me-experimental" ]] ||
/home/runner/work/_temp/4b187817-0de6-48c1-a0f0-cd08f3e6d9ce.sh: line 3: conditional binary operator expected
Error: Process completed with exit code 2.
```

**Comment by oconnorjoseph** [comment] 2024-12-16 06:13
This actually happen for Issues too. It appears to be happening for anytime you prompt @openhands-agent via a GitHub comment.

**Comment by enyst** [comment] 2024-12-16 07:24
@openhands-agent-exp what do you think?

**Comment by openhands-agent** [comment] 2024-12-16 07:24
[OpenHands](https://github.com/All-Hands-AI/OpenHands) started fixing the issue! You can monitor the progress [here](https://github.com/All-Hands-AI/OpenHands/actions/runs/12347846794).

**Comment by openhands-agent** [comment] 2024-12-16 07:28
An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named 'openhands-fix-issue-5621' has been created with the attempted changes. You can view the branch [here](https://github.com/All-Hands-AI/OpenHands/tree/openhands-fix-issue-5621). Manual intervention may be required.

**Comment by malhotra5** [comment] 2024-12-17 01:47
I think the root cause for this may actually be related to #5230 (the error messages look familiar)

I have a PR out for this in #5641, let's see if it resolves the issue!

**Comment by mamoodi** [comment] 2024-12-19 19:56
@malhotra5 since the PR has merged and released, do you think this is good to close?

**Comment by malhotra5** [comment] 2024-12-19 20:47
I think we're good to close!

**Closed by malhotra5** 2024-12-19 20:47 UTC
Labels: bug, resolver
