### ISSUE TITLE
[Bug]: Issue with BrowserOutputObservation

### ISSUE THREAD

**Issue by rbren** [All-Hands-AI/OpenHands#4677] opened 2024-11-01 12:07 UTC
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Describe the bug and reproduction steps

The browser agent kicked off randomly. I tried to pause, and then stop (neither worked, but not the point of this issue). Big problem is I ended up in an unrecoverable state, and had to start a new session. Here are the logs
```
openhands-768dd55cfc-6wgj8 openhands [Agent Controller e4ecff18-c2d0-445a-b330-4f9c792fd78e] LEVEL 0 LOCAL STEP 15 GLOBAL STEP 15
openhands-768dd55cfc-6wgj8 openhands
openhands-768dd55cfc-6wgj8 openhands Traceback (most recent call last):
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/controller/agent_controller.py", line 168, in start_step_loop
openhands-768dd55cfc-6wgj8 openhands     await self._step()
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/controller/agent_controller.py", line 464, in _step
openhands-768dd55cfc-6wgj8 openhands     action = self.agent.step(self.state)
openhands-768dd55cfc-6wgj8 openhands              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 332, in step
openhands-768dd55cfc-6wgj8 openhands     messages = self._get_messages(state)
openhands-768dd55cfc-6wgj8 openhands                ^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 417, in _get_messages
openhands-768dd55cfc-6wgj8 openhands     messages_to_add = self.get_observation_message(
openhands-768dd55cfc-6wgj8 openhands                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 286, in get_observation_message
openhands-768dd55cfc-6wgj8 openhands     raise ValueError(f'Unknown observation type: {type(obs)}')
openhands-768dd55cfc-6wgj8 openhands ValueError: Unknown observation type: <class 'openhands.events.observation.browse.BrowserOutputObservation'>
openhands-768dd55cfc-6wgj8 openhands 12:00:50 - openhands:ERROR: agent_controller.py:135 - [Agent Controller e4ecff18-c2d0-445a-b330-4f9c792fd78e] Error while running the agent: Unknown observation type: <class 'openhands.events.observation.browse.BrowserOutputObservation'>
openhands-768dd55cfc-6wgj8 openhands 12:00:50 - openhands:ERROR: agent_controller.py:135 - [Agent Controller e4ecff18-c2d0-445a-b330-4f9c792fd78e] Traceback (most recent call last):
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/controller/agent_controller.py", line 168, in start_step_loop
openhands-768dd55cfc-6wgj8 openhands     await self._step()
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/controller/agent_controller.py", line 464, in _step
openhands-768dd55cfc-6wgj8 openhands     action = self.agent.step(self.state)
openhands-768dd55cfc-6wgj8 openhands              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 332, in step
openhands-768dd55cfc-6wgj8 openhands     messages = self._get_messages(state)
openhands-768dd55cfc-6wgj8 openhands                ^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 417, in _get_messages
openhands-768dd55cfc-6wgj8 openhands     messages_to_add = self.get_observation_message(
openhands-768dd55cfc-6wgj8 openhands                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openhands-768dd55cfc-6wgj8 openhands   File "/app/openhands/agenthub/codeact_agent/codeact_agent.py", line 286, in get_observation_message
openhands-768dd55cfc-6wgj8 openhands     raise ValueError(f'Unknown observation type: {type(obs)}')
openhands-768dd55cfc-6wgj8 openhands ValueError: Unknown observation type: <class 'openhands.events.observation.browse.BrowserOutputObservation'>
openhands-768dd55cfc-6wgj8 openhands
openhands-768dd55cfc-6wgj8 openhands 12:00:50 - openhands:INFO: agent_controller.py:135 - [Agent Controller e4ecff18-c2d0-445a-b330-4f9c792fd78e] Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.ERROR

```

### OpenHands Installation

Docker command in README

### OpenHands Version

main

### Operating System

None

**Comment by amanape** [comment] 2024-11-01 12:08
IMO we should disable the browser agent and its functionalities until it is more stable and predictable. WDYT?

cc: @xingyaoww @neubig

**Comment by xingyaoww** [comment] 2024-11-01 12:27
The cause of this issue is actually pretty weird -- CodeAct cannot produce BrowseInteractiveAction, then where the CmdOutputObservation comes from?

Anyway - I'll try to see if i can get https://github.com/All-Hands-AI/OpenHands/pull/4667 in today - if so, we could just completely solve this issue & we don't need to temporarily disable browsing today

**Comment by enyst** [comment] 2024-11-01 12:45
@xingyaoww It's because when the delegate ends with an error, it doesn't finish normally and its last event ends up in the parent agent.
- fixed in https://github.com/All-Hands-AI/OpenHands/pull/3808/

**Closed** 2024-11-04 15:37 UTC
Labels: bug, severity:medium
